#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
# python -u streamlit_app.py "$@"
streamlit run streamlit_app.py "$@"
